import Head from "next/head";
import Link from "next/link";
import ScrollyVideo from "scrolly-video/dist/ScrollyVideo.cjs.jsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-slate-300">
        {/*  */}
        <div className="flex gap-5 max-w-3xl mx-auto justify-between mt-10">
          <div className=" flex flex-col gap-6 text-white pr-52">
            <div className=" flex items-center gap-4 mb-16 font-light">
              <Link href={"/"} className=" text-4xl">
                1000
              </Link>{" "}
              <span className="text-3xl font-thin text-glow">PARK</span>
            </div>
            <div>
              <p className=" font-semibold text-lg">FLOATY AND NIMBLE</p>
              <p className=" font-thin">
                Designed for those who want their powder skis to feel light and
                nimble without compromising the ability to float in deep powder.
              </p>
            </div>
            <div className=" flex flex-col">
              <p className="font-semibold text-lg">
                SPECIFICATIONS AT A GLANCE
              </p>
              <p className=" font-thin">Width: 117mm under foot</p>
              <p className=" font-thin">Available lengths: 180 & 188cm</p>
              <p className=" font-thin">Turning radius: 17 & 19m</p>
              <p className=" font-thin">Price: €899 (free shipping)</p>
            </div>
            <div className=" flex flex-col gap-5 text-black">
              <select name="" id="" className=" w-52">
                <option value="">In-stock 180cm</option>
                <option value="">In-stock 188cm</option>
              </select>
              <button className=" rounded-md w-40 text-sm bg-black text-white p-3">
                899€ - BUY NOW
              </button>
            </div>
          </div>
        </div>
        {/*  */}

        {/*  */}
        <div className={"mt-20"} style={{ height: "400vh" }}>
          <ScrollyVideo full={true} src="/vid01.mp4" />
        </div>
        {/*  */}

        {/*  */}
        <div className="flex gap-5 max-w-3xl mx-auto mt-20 text-white flex-col">
          <h1 className=" text-4xl">THE FEELING</h1>
          <p className=" font-thin">
            Unexpectedly easy to maneuver. <br /> A powder ski that truly feels
            light on your feet and lets you <br /> play around effortlessly in
            deep snow.
          </p>
        </div>
        {/*  */}

        {/*  */}
        <div className={" mt-20"} style={{ height: "400vh" }}>
          <ScrollyVideo full={true} src="/vid02.mp4" />
        </div>
        {/*  */}

        {/*  */}
        <div className="flex gap-5 max-w-3xl mx-auto mt-20 text-white flex-col">
          <h1 className=" text-4xl">WHAT MAKES THE FEELING</h1>
          <p className=" font-thin">
            Our riders and design team are proud to present a powder ski that,
            thanks to its torsional softness, is extremely quick and easy to
            handle. The ski features early rise tip and tail to keep you afloat
            both forwards and backwards. We cut the steel edges off at the nose
            and tail to save weight and keep unnecessary vibrations out of the
            equation.
          </p>
          <p className=" font-thin mt-5">
            With a thin bamboo and poplar wood core the 1000 powder ski is
            light, agile and floaty.
          </p>
        </div>
        {/*  */}

        {/*  */}
        <div className={" mt-20"} style={{ height: "400vh" }}>
          <ScrollyVideo full={true} src="/vid01.mp4" />
        </div>
        {/*  */}

        {/*  */}
        <div className=" font-extralight grid grid-cols-2 max-w-5xl mx-auto text-white gap-20 justify-center">
          <div className=" text-xl flex flex-col items-center">
            <div>
              <h1 className=" text-5xl">
                180<span className=" text-base">cm</span>
              </h1>
              <p>Turning radius: 17m</p>
              <p>Dimensions: 144-117-140mm</p>
              <p>Weight: 2054g</p>
              <p>Core: Bamboo & Poplar wood</p>
              <p>Edge thickness: 2,2mm</p>
              <p>Base thickness: 1,4mm</p>
              <p>Flex: Soft</p>
              <p>Profile: Camber and rocker combo</p>
            </div>
          </div>
          <div className=" text-xl flex flex-col items-center">
            <div>
              <h1 className=" text-5xl">
                188<span className=" text-base">cm</span>
              </h1>
              <p>Turning radius: 19m</p>
              <p>Dimensions: 144-117-140mm</p>
              <p>Weight: 2155g</p>
              <p>Core: Bamboo & Poplar wood</p>
              <p>Edge thickness: 2,2mm</p>
              <p>Base thickness: 1,4mm</p>
              <p>Flex: Soft</p>
              <p>Profile: Camber and rocker combo</p>
            </div>
          </div>
        </div>
        {/*  */}
      </main>
    </>
  );
}
